package com.termux.app.terminal.ai;

import com.termux.shared.logger.Logger;
import com.termux.shared.termux.TermuxConstants;

import java.io.File;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;

public final class TermuxAiCliInstaller {

    private static final String LOG_TAG = "TermuxAiCliInstaller";

    private TermuxAiCliInstaller() {}

    public static void installIfPossible() {
        File binDir = TermuxConstants.TERMUX_BIN_PREFIX_DIR;
        if (!binDir.isDirectory()) return;

        write("termux-ai", "#!/system/bin/sh\n" +
            "# Generated by termux-ai.\n" +
            "CMD=\"$1\"\n" +
            "shift 2>/dev/null || true\n" +
            "exec /system/bin/am broadcast --receiver-foreground " +
            "-n com.termux/com.termux.app.terminal.ai.TermuxAiCommandReceiver " +
            "-a com.termux.AI_COMMAND --es cmd \"$CMD\" \"$@\"\n");
        write("termux-ai-info", "#!/system/bin/sh\nexec termux-ai sys.info\n");
        write("termux-ai-battery", "#!/system/bin/sh\nexec termux-ai sys.battery\n");
        write("termux-ai-clipboard", "#!/system/bin/sh\n" +
            "case \"$1\" in\n" +
            "  set) shift; exec termux-ai sys.clipboard.set --es text \"$*\" ;;\n" +
            "  *) exec termux-ai sys.clipboard.get ;;\n" +
            "esac\n");
        write("termux-ai-vibrate", "#!/system/bin/sh\nexec termux-ai sys.vibrate --ei duration_ms \"${1:-80}\"\n");
        write("termux-ai-notify", "#!/system/bin/sh\nexec termux-ai sys.notify --es title \"${1:-termux-ai}\" --es body \"${2:-}\"\n");
        write("termux-ai-sensor", "#!/system/bin/sh\n" +
            "case \"$1\" in\n" +
            "  read) exec termux-ai sensor.read --es type \"${2:-accelerometer}\" ;;\n" +
            "  *) exec termux-ai sensor.list ;;\n" +
            "esac\n");
    }

    private static void write(String name, String content) {
        File file = new File(TermuxConstants.TERMUX_BIN_PREFIX_DIR, name);
        try (FileOutputStream out = new FileOutputStream(file)) {
            out.write(content.getBytes(StandardCharsets.UTF_8));
            file.setExecutable(true, false);
        } catch (Exception e) {
            Logger.logStackTraceWithMessage(LOG_TAG, "Failed to install " + name, e);
        }
    }
}
